### ISSUE TITLE
Stand von Master- und Develop-Branch verfügbar machen

### ISSUE THREAD

**Issue by Bensk1** [Strassengezwitscher/Strassengezwitscher#11]
- nach erfolgreichem automatisiertem Build (Linting, Tests, etc) soll der Stand des Master über unseren Server verfügbar gemacht werden
- Master kann öffentlich zugänglich sein
- Develop sollte geschützt sein (z. B.: htaccess)

**Comment by Bensk1** [comment]
Abgeschlossen?

**Comment by piepmatz** [comment]
Wir haben jetzt Badges in der Readme auf der Github-Projektseite.
- Bei einem Commit führt Travis alle Tests aus. Falls es sich dabei um den Master- oder Developbranch gehandelt hat und alle Tests erfolgreich durchliefen, wird der Branch sofort auf dem Server deployed.
- Außerdem wird im Anschluss die Testabdeckung geprüft.
- Ein weiterer Dienst hält Ausschau nach Code Smells usw.

Der Masterbranch ist verfügbar unter http://streetcoverage.org. Weil der Domainumzug noch nicht beendet ist, erreicht ihr in auch unter http://sg, dafür müsst ihr die `/etc/hosts` anpassen.
Der Developbranch ist verfügbar unter http://dev.streetcoverage.org sowie unter http://sgdev.
Folgendes für eure `/etc/hosts`:
```
5.45.110.119 sg
5.45.110.119 sgdev
```
Der Developbranch ist durch ein Passwort geschützt, das kriegt ihr auf einem anderen Kanal.
Der Master ist öffentlich zugänglich.

Wenn ihr selbst deployen wollt, könnt ihr das auf zwei Arten tun:
- Loggt euch auf dem Server als User `deploy` ein, in dessen Homeverzeichnis findet ihr die zwei Skripte, um den Master- oder Developbranch zu deployen. Ruft diese mit `sudo` auf. Ich brauche also noch ein paar Public Keys von euch, wenn ihr euch einloggen wollt. :)
- Wir haben ein zweites Repository fürs Deployment: https://github.com/Strassengezwitscher/deployment
  - Damit können nicht nur beide Branches deployed werden, sondern auch ein Großteil des gesamten Servers, also Konfiguration von nginx, uwsgi, die Unterstützung fürs Deployment durch Travis usw.
  - Zukünftige Konfigurationsänderungen nehmen wir also nicht mehr live am Server vor, sondern pflegen diese ins Repo ein.
  - Zum Aufruf des Deployments liegt ein einfaches Skript bei. Da aber ein paar geschützte Daten (Passwörter) nötig sind, habe ich diese nicht mit ins Repo aufgenommen, auch die kriegt ihr auf einem anderen Kanal.

**Comment by Bensk1** [comment]
Sehr nice!
