### ISSUE TITLE
Djangosuit verwenden

### ISSUE THREAD

**Issue by mathebox** [Strassengezwitscher/Strassengezwitscher#111]
Um uns Arbeit abzunehmen sollten wir [djangosuit](http://djangosuit.com/) verwenden

**Comment by piepmatz** [comment]
Was schmerzt am Default-Admin-Theme?

**Comment by mathebox** [comment]
Djangosuit bringt auch eine Filterfunktion mit. Die könnte hilfreich sein, wenn wir mit der initialen Fixture-Datei arbeiten.
