### ISSUE TITLE
Refactoring von Serializer von facebookpage und event

### ISSUE THREAD

**Issue by mathebox** [Strassengezwitscher/Strassengezwitscher#112]
Im Angular-Teil wird für beide Modelle die gleiche `MapObject`-Klasse verwendet. Deshalb sollte auch im Backend das gleich Serializer verwendet werden.

**Comment by piepmatz** [comment]
Der Serializer bestimmt doch aber, welche Felder im JSON landen. Momentan sind das für FacebookPages und Events nur jene, die von MapObject geerbt wurden.
Nun haben beide aber weitere Felder, die irgendwann vermutlich auch im JSON landen werden, wenn sie denn benötigt werden. Dann werden, wie schon jetzt vorhanden, verschiedene Serializer benötigt.
Statt beide im Backend zusammenzufassen, würde ich eher davon ausgehen, dass im Frontend demnächst auch zwischen Event und FacebookPage unterschieden wird.

**Comment by piepmatz** [comment]
@mathebox: Kann das zu?

**Comment by mathebox** [comment]
Ja. Sollte mit #322 gelöst werden
