### ISSUE TITLE
Styleguides für Code

### ISSUE THREAD

**Issue by mathebox** [Strassengezwitscher/Strassengezwitscher#12]
- [x] Python: [PEP 8](https://www.python.org/dev/peps/pep-0008/)
- [x] Typescript: [Excel Micro based on AirBnB JS-Style Guide](https://github.com/excelmicro/typescript)

Linter for Styleguides (Voraussetzung: #14 )
- [x] Linter für Python
- [x] Linter für JavaScript

**Comment by piepmatz** [comment]
Zu Python:
Für unsere Code Health Checks nutzen wir bereits Landscape.io. Deren Kerntool [prospector](https://github.com/landscapeio/prospector) kombiniert pylint, pep8 und weitere. prospector wird über pip installiert, kann also jeder lokal laufen lassen. Schön ist auch, dass verschiedene strictness-levels eingestellt werden können, wie kleinlich die Checks also sein sollen.
