### ISSUE TITLE
Graphische Unterscheidung zwischen vergangenen und kommenden Veranstaltungen

### ISSUE THREAD

**Issue by Bensk1** [Strassengezwitscher/Strassengezwitscher#127]

**Comment by ChristopherSchmidt89** [comment]
"bei Veranstaltungen: vergangene und bevorstehende Veranstaltungen sollten irgendwie voneinander abgetrennt werdern, z.B. farblich. Oder zusätzlich z.B. größenmäßig: Je näher iene Veranstaltung, desto größer das Symbol."

**Comment by Bensk1** [comment]
Für den MVP genügt eine farbliche Unterscheidung. Vergangene Veranstaltungen werden verblasst (durch leichte Transparenz), noch kommende in voller Farbe dargestellt.

**Comment by Bensk1** [comment]
See #225
