### ISSUE TITLE
Simple Webseite während der Entwicklung

### ISSUE THREAD

**Issue by mathebox** [Strassengezwitscher/Strassengezwitscher#13]
Bis zur ersten Version, könnte auf der Webseite zB der Text "Hier entsteht die neue Webseite von Straßengezwitscher." angezeigt werden.

Das wäre dann der aktuelle Stand vom master-branch. Entwickeln würden wir auf dem develop-branch.

**Comment by Bensk1** [comment]
Zur Zeit zeigt die Webseite auf den Twitteraccount, was eine ganz ordentliche Lösung ist, wie ich finde.

Die Umstellung der DNS-Records auf den Master unseres Server kann dann mit Fertigstellung einer MVP-Version vollzogen werden.

**Comment by mathebox** [comment]
Eine andere Lösung wäre, erst nach 10 Sekunden auf den Twitteraccount weiterzuleiten, um so die neue Seite anzukündigen.

**Comment by Bensk1** [comment]
+1

Von meinem iPhone gesendet

**Comment by humuzz** [comment]
Könntet ihr bitte, solange ihr die Seite einrichtet, wieder die Weiterleitung zum Twitteraccount einstellen? Im Moment ist da eine "Welcome to nginx!"-Seite.

**Comment by Bensk1** [comment]
Das war ich vorhin, kommt sofort!

**Comment by humuzz** [comment]
Danke :) Kein Stress, hatte mich nur gewundert!

**Comment by Bensk1** [comment]
Sollte erledigt sein
