### ISSUE TITLE
Repository umbenennen

### ISSUE THREAD

**Issue by mathebox** [Strassengezwitscher/Strassengezwitscher#130]
Wir programmieren ja die `Crowdgezwitscher`-Plattform.

Danach müssen wir aber alle dir origin-Url im git aktualisieren.

**Comment by mathebox** [comment]
Inklusive:
- Links in `package.json` anpassen
- Links in `README.md` anpassen

**Comment by piepmatz** [comment]
Inklusive: Playbooks im deployment Repo anpassen
