### ISSUE TITLE
Beschreibung der Verschluesselung im Kontaktformular

### ISSUE THREAD

**Issue by ChristopherSchmidt89** [Strassengezwitscher/Strassengezwitscher#132]
Bessere Platzierung der Info, dass die Nachricht PGP verschlüsselt wird.

**Comment by mathebox** [comment]
Das baue ich gleich in #114 mit ein

**Comment by ChristopherSchmidt89** [comment]
Text sollte folgender sein, ist atm in dem Tooltip beim Submit versteckt und hier leicht angepasst (mit Alexej so abgestimmt)
"Ihre valide Nachricht wird immer PGP verschlüsselt an uns übertragen. Um eine verschlüsselte Antwort zu erhalten, fügen Sie bitte der Nachricht Ihren eigenen GPG Public Key im Anhang hinzu."

**Comment by piepmatz** [comment]
`PGP-verschlüsselt` entweder mit Bindestrich oder aber `mit PGP verschlüsselt` ;)
**als** Anhang fände ich auch besser.
