### ISSUE TITLE
UX - Workflow Improvement Contact Form

### ISSUE THREAD

**Issue by ChristopherSchmidt89** [Strassengezwitscher/Strassengezwitscher#137]
Als Nutzer bleibe ich nach erfolgreichem Submit auf der Kontaktformular Seite und erhalte eine Success Message, die Felder sind alle clean.

**Comment by piepmatz** [comment]
Müsste mal mit @humuzz besprochen werden, wie sie es am liebsten hätten.
- was soll nach erfolgreichem Senden angezeigt werden: Umleitung? Wohin? Eigene Seite nur mit Bestätigung? Abgeschickte Nachricht anzeigen?

**Comment by humuzz** [comment]
Eine einfache Bestätigung: "Ihre Nachricht wurde erfolgreich gesendet." Darunter ein Link "Zurück zur Startseite".
