### ISSUE TITLE
Automatisierungstool

### ISSUE THREAD

**Issue by mathebox** [Strassengezwitscher/Strassengezwitscher#14]
Wir brauchen höchstwahrscheinlich ein Automatisierungtool um Aufgaben einfach auszuführen, die nicht direkt Django betreffen, zB:

- Code Linter
- (Generierung von Dokumentation)
- ...

Folgende Tool würden sich anbieten:
- [grunt](http://gruntjs.com)
- [gulp](http://gulpjs.com)

Beide sind über `npm` verfügbar. Unterschiede von grunt und gulp findet man [hier](http://sixrevisions.com/web-development/grunt-vs-gulp/).
Alternativen sind willkommen.

**Comment by Bensk1** [comment]
Wir haben uns für Gulp entschieden. Das Tool muss mindestens folgende Aufgaben übernehmen:

- [ ] übersetzen von TypeScript in JavaScript
- [ ] erstellen eines Mappings zum besseren Debugging
- [ ] Linting des Codes

weitere Tasks können optional erfüllt werden:

- [ ] Komprimierung des Javascript
- [ ] automatische Syntax-Korrektur
- [ ] Einbinden der komprimierten JavaScript-Abhängigkeiten

Bitte ergänzen!
