### ISSUE TITLE
Landing-Page für den internen Bereich

### ISSUE THREAD

**Issue by mathebox** [Strassengezwitscher/Strassengezwitscher#140]
Aktuell gibt es da nur eine leere Seite.

Dabei kann gleich die Navbar angepasst werden.
- Link auf "Admin" führt zum User Bereich, sollte aber zur Landing page leiten.
- Optional: Link zum User Bereich

**Comment by piepmatz** [comment]
Inhalt, z.B.:
- Anzahl unbestätigter Events/FacebookPages
--> also eine Art Dashboard
