### ISSUE TITLE
Scripte nach HTML laden

### ISSUE THREAD

**Issue by piepmatz** [Strassengezwitscher/Strassengezwitscher#148]
Die Scripts sollen nach dem HTML geladen werden, also am Ende der Dateien eingebunden werden.
Ist Best Practice weil schneller und sicherer (falls das JS auf dem DOM arbeitet).

**Comment by mathebox** [comment]
`defer` sollte auch reichen. http://www.w3schools.com/tags/att_script_defer.asp
