### ISSUE TITLE
Frontend-Technologien festlegen

### ISSUE THREAD

**Issue by mathebox** [Strassengezwitscher/Strassengezwitscher#15]
Zum einem müssen wir uns auf die Programmiersprache einigen:
- [ES6](https://github.com/lukehoban/es6features#readme) (Browser-Support ist [unterwegs](http://kangax.github.io/compat-table/es6/).)
- [CoffeeScript](http://coffeescript.org)
- [TypeScript](http://www.typescriptlang.org)
- ...

Zum anderen brauchen wir (vielleicht) ein ganzes Framework für das Frontend:
- [Angular](https://angularjs.org)
- ...

**Comment by tgraupne** [comment]
Ich dachte die Technologiefragen wären schon geklärt?

**Comment by mathebox** [comment]
Für das Backend, ja. Aber je nach Komplexität werden wir auch auf der Client-Seite Logic haben und da haben wir uns noch nicht geeinigt.

Leider wurde das Aufsetzen des Tools für die Gruppenkommunikation etwas verhindern - lag nicht an uns. Nächste Woche sollten wir das haben und dann können wir uns besser koordinieren.
Bis dahin sollen die Issues hier auch daran erinnern, was wir noch besprechen sollten.

**Comment by tgraupne** [comment]
Alles klar, danke für's Abholen.

**Comment by Bensk1** [comment]
Um das mal ins Rollen zu bringen:
CoffeeScript hat meiner Meinung nach keinen Vorteil gegenüber TypeScript oder ES6. 

TypeScript vs. ES6:
- TypeScript setzt auf statische Typisierung, was ich als Vorteil sehe
- TypeScript bietet eigentlich alle Features von ES6 und kann bei voller Unterstützung von ES6 durch die JavaScript Engines auch in ES6 übersetzt werden 
- ES6 ist noch nicht vollständig in allen Browsern unterstützt (vor allem Sorge bereitet mir die Abdeckung bei nicht wirklich alten Android-Geräten)
- TypeScript muss immer übersetzt werden. Momentan zu ES5, bald in ES6. Hingegen kann ES6 demnächst direkt ausgeführt werden

Ich denke, dass beide Möglichkeiten von technologischer Sicht her, eine vernünftige Wahl wären. Bei ES6 macht mir nur der Browser-Support Kopfschmerzen, weil wir ja ein Portal für möglichst alle Anwender bauen möchten. 

Ich denke, dass wir ein Frontend-Framework benötigen werden und kenne mich nur mit Angular aus. 

Um Eure Meinungen wird ausdrücklich gebeten.

**Comment by piepmatz** [comment]
Ich spreche mich gegen reines JavaScript (also vor ES6) aus.

Mir haben folgende Slides einen kurzen Überblick gegeben: http://de.slideshare.net/NeilGreen1/type-script-vs-coffeescript-vs-es6.

CoffeeScript hat mich nicht so umgehauen, ES6 selbst und TypeScript gefallen mir besser. Aus dem von @mathebox oben verlinkten [Vergleich](https://kangax.github.io/compat-table/es6/) geht hervor, dass der Großteil der aktuellen Android-Geräte (5.x) niemals in den Genuss von ES6 kommen werden. Das könnte ein K.o.-Kriterium sein.
Auch sieht es dort so aus, als ob TypeScript erst zu 60% ES6 unterstützt?

Im oben erwähnten Slidedeck gibts folgenden Satz: "If you want to use ES6 features in all browser now use Babel" Hat jemand eine Meinung zu Babel?

Fazit: TypeScript sagt mir am ehesten zu.

Zum Frontend-Framework: Wer kennt sich damit von uns am ehesten aus? @mathebox vielleicht? Ich kann da außer "den Namen kenne ich" bislang nicht viel beitragen.

**Comment by mathebox** [comment]
Ich habe bisher nur mit der Kombination ES6 (+ Babel) + jQuery gearbeitet.
Wenn wir möglichst alle Browser unterstützen wollen, werden wir wohl nicht am einem Compiler drumrum kommen. Ich glaube, das ist auch okay so.
Ich bin also für auch TypeScript oder ES6.

Wichtiger ist, glaube ich, die Frage zum Frontend Framework und ob wir eins brauchen. Auch Beeinflusst von #17. Dafür sollten wir mal klären, wie komplex das Frontend werden wird.
Ich

**Comment by Bensk1** [comment]
Da der Translator sowohl bei ES6 als auch bei TypeScript benötigt werden würde, läuft es meiner Meinung nach auf statische Typisierung (TypeScript) vs. "Benny und Max haben schon Erfahrung mit der Technologie " (ES6) hinaus. 

Ich denke, dass wir mit keiner von beiden Technologien etwas falsch machen würden. Wir sollten uns nur bald entscheiden.

**Comment by Bensk1** [comment]
Habemus papam! TypeScript + AngularJS
