### ISSUE TITLE
Zusätzliche Frontendseiten

### ISSUE THREAD

**Issue by ChristopherSchmidt89** [Strassengezwitscher/Strassengezwitscher#153]
Hinzufügen vom Button für "Spenden"
- dazu benötigen wir noch einen PayPal.me Link (oder ähnliches) @humuzz 

Hinzufügen des Menüpunkts "Über uns"
- hier bräuchten wir dann einen passenden Text @humuzz 

Hinzufügen des Menüpunkts "Impressum"
- hier bräuchten wir dann einen passenden Text @humuzz

**Comment by humuzz** [comment]
Spenden: paypal.me/strassengezwitscher

**Comment by humuzz** [comment]
Können wir den "Über uns"-Text kurz vor VÖ reinsetzen?

**Comment by Bensk1** [comment]
Klar!
