### ISSUE TITLE
Twitterintegration

### ISSUE THREAD

**Issue by ChristopherSchmidt89** [Strassengezwitscher/Strassengezwitscher#154]
Twitter Feed für Events anzeigen in der Infobox, siehe #149 zum Beispiel in seitlichem Overlay

Anpassung im Backend, Speichern eines Twitterhashes im MapObject ?

**Comment by ChristopherSchmidt89** [comment]
Welche Informationen können wir aus der Twitter API rausziehen?
Wie können wir die Rate Limits handeln ? 15 Requests per 15 Min Window 
(https://dev.twitter.com/rest/public/rate-limiting)

**Comment by mathebox** [comment]
Brauchen wir dafür nicht auch eine Liste von Hashtags?

**Comment by humuzz** [comment]
Die Filterung muss ja für jedes Event angepasst werden. Twitter-Feeds gibts ja nur, wenn entweder einer der Straßengezwitscher-Accounts (@streetcovderage, @coverage_che oder @coverage_le ) oder ein anderer, verifizierter Account twittert. Die Filter findet daher nach folgenden Kriterien statt: Username, Zeitraum und Hashtag(s), die von dem Moderator/Admin eingetragen werden müssen.
