### ISSUE TITLE
Django Template Engine wechseln

### ISSUE THREAD

**Issue by mathebox** [Strassengezwitscher/Strassengezwitscher#17]
Es kann sein, dass wir während der Entwicklung sowohl im Backend als auch im Frontend Templates verwenden wollen. Genau würde das bedeuten:
- Backend Templates: Der Server liefert fertiges HTML aus, das dann einfach angezeigt wird.
- Frontend Templates: Der Server liefert das Template und JSON aus, dann im im Frontend gerendert.

Je nach Anwendungsfall passt eine Methode besser.
Es wäre aber unschön, wenn wir zwei verschiedene Template Engines verwenden müssten. Es ist besser wir wechseln auf eine, die im Frontend und Backend unterstützt wird.

Die - meiner Meinung nach - beste Alternative ist [Jinja](http://jinja.pocoo.org/docs/dev/), die der Django Template Engine sehr ähnlich ist.

Weitere Links:
- [Unterschiede Jinja - Django](http://jinja.pocoo.org/docs/dev/switching/#django)
- JavaScript Libs fürs Frontend: [NunJunks](http://mozilla.github.io/nunjucks/) oder [JinJS](https://github.com/ravelsoft/node-jinjs) (beide noch nicht getestet)

**Comment by Bensk1** [comment]
Sind spezielle Frontend Templates nötig, wenn wir Angular nutzen? Das kommt ja eigentlich schon mit Templates?

**Comment by mathebox** [comment]
Angenommen wir verwenden Angular.js, dann haben wir genau den Fall, dass wir zwei verschiedene Template-Varianten verwenden können. Einmal die von Django und einmal die von Angular.js. Das wird's schnell zur Verwirrung führen.

**Comment by piepmatz** [comment]
Verschiedene Template-Sprachen dürften nicht nur zu Verwirrung führen, sondern auch zu Syntax-Konflikten. Die verwendeten Symbole lassen sich aber z.B. bei Jinja und Angular anpassen: https://stackoverflow.com/questions/30362950/is-it-possible-to-use-angular-with-the-jinja2-template-engine

So angenehm ich Jinja auch finde, würde ich nicht davon die Wahl der Frontend-Templates abhängig machen. Von NunJunks und JinJS (das tot zu sein scheint) habe ich noch nie gehört, für Angular dürften wir deutlich mehr Material und Hilfen finden.
Andererseits: Zu welchem Zwecke brauchen wir ein Frontend-Framework? Wenns bloß um die Templates geht, spricht nichts gegen bspw. Jinja. Wenn wir aber deutlich mehr Funktionalitäten von z.B. Angular nutzen wollen, würde ich nicht an Jinja hängen. Ich traue uns schon zu, dass wir zwei Template-Sprachen gehandled kriegen.

**Comment by BenReissaus** [comment]
Ich bin etwas verwirrt über den Gesprächsverlauf hier. Daher klärt mich bitte auf. Grundsätzlich ist es doch so:
Eine Template Engine sorgt letztendlich dafür, dass ein HTML-Template mit Daten befüllt wird. Das kann im Backend passieren oder im Frontend. Django bietet die Möglichkeit, HTML-Templates im Backend mit Daten zu befüllen und fertiges HTML ans Frontend zu senden. Es benutzt dafür eine eigene Template Engine. 
Jinja ist eine Template Engine, die in Python benutzt werden kann und zwar ebenfalls im Backend. Meine Frage: Warum sollten wir Django's default template engine durch eine andere backend template engine ersetzen?

Ein weiterer Punkt zu den Konflikten zwischen Frontend und Backend Template Engines: Ich bin ebenfalls der Meinung, dass wir nur eins von beidem benutzen sollten. Ein für mich attraktives Setup wäre zum Beispiel das folgende: Wir nutzen Django mit einer Rest API im Backend und AngularJS im Frontend. Wir würden also angular templates benutzen, die von django ausgelieft werden (aber keine django template engine benötigen) und die im Frontend von angular mit JSON-Daten befüllt werden. Dann sollte es zu keinen Konflikten kommen, oder?

Warum ich für Frontend-Rendering bin: Je dynamischer eine Webseite ist und je mehr sie "data-driven" ist, desto eher macht es für mich sinn im Frontend zu rendern. Ich denke da gerade an die Map mit Pins, die vom Zoom abhängig angepasst/geladen werden bzw. der Feed von Tweets etc. 

Und um gleich noch typescript vs ES6 hier einzubringen: AngularJS nutzt wohl Typescript.

**Comment by Bensk1** [comment]
Ich glaube es ging darum, dass wir Djanos Default Template Engine durch eine andere ersetzen, um die gleiche Template Engine wie im Frontend zu nutzen, falls dort eine genutzt wird. 

Ich kenne mich nicht aus mit dem typischen Django Weg, hätte es jetzt aber intuitiv auch so gemacht, wie es Benny schildert: Angular Views mit Django ausliefern, die dann im Frontend gerendert werden und ggf. Daten als JSON von einer Rest API anfordern.

**Comment by piepmatz** [comment]
Genau so ist es meines Wissens nach auch gedacht.
Aber: Django Templates können ja deutlich mehr als Variablen durch ihre Werte zu ersetzen. Viele HTML-Seiten sind ja ähnlich aufgebaut, z.B. haben alle den gleichen Footer, sodass der Footer nur einmal gebaut wird und dann in den anderen Templates referenziert wird. Das reicht schon, um einen Mix aus Django-Template-Sprache/Jinja und Angular zu haben.

**Comment by mathebox** [comment]
Ja Jan richtig, das meinte ich damit.

Der Weg, den ihr meint, hört sich auch vernünftig an. Ich möchte nur, dass wir uns auf eine vernünftige Methode einigen.  Außerdem weiß ich nicht, ob wir, wenn wir Django nur via REST-API ansprechen, Features aufgeben würden.

**Comment by Bensk1** [comment]
Das angesprochene Problem mit dem Footer sollte sich auch mit reinem Angular oder JavaScript selbst lösen lassen.

Grundsätzlich müssen wir ja bei Django keine Templates oder Features deaktivieren, sondern können sie nutzen, falls wir sie benötigen?

**Comment by Bensk1** [comment]
Django-Template werden an den Stellen genutzt, an denen es Sinn ergibt. Grundsätzlich versuchen wir mittels Django REST Framework eine API zu erstellen, die von unseren Frontend-Controllern abgefragt wird, die wiederum, insbesondere bei datenintensiven Unterseiten, das Rendering übernehmen.
