### ISSUE TITLE
Blog-Eintrag anlegen

### ISSUE THREAD

**Issue by Bensk1** [Strassengezwitscher/Strassengezwitscher#175]
Als Admin möchte ich im Betreiberbereich Blog-Einträge inkl. Bilder mit einem WYSIWYG-Editor anlegen können. Auch eine Überschrift möchte ich vergeben. Weiterhin soll es möglich sein andere Nutzer des Betreiberbereichs als Autoren anzugeben.

**Comment by mathebox** [comment]
Attribute für die erste Version:
- Überschrift
- Text
- Autor/User

**Comment by BenReissaus** [comment]
Issues to complete:
- [ ] [#235](https://github.com/Strassengezwitscher/Strassengezwitscher/issues/235)
- [ ] [#236](https://github.com/Strassengezwitscher/Strassengezwitscher/issues/236)
