### ISSUE TITLE
Keine Map mit Firefox wegen Cross-Origin-Ärger

### ISSUE THREAD

**Issue by piepmatz** [Strassengezwitscher/Strassengezwitscher#18]
Firefox zeigt auf http://sgdev keine Map an.

Grund: Die Karte soll mit jQuery geladen werden. jQuery kann aber nicht geladen werden, da es von extern geladen wird und wir dadurch Cross-Origin-Probleme kriegen.

Fix:
- Option 1: nginx schickt einen Header mit, der das Laden über Cross-Origin erlaubt.
- Option 2: Wir packen jQuery mit ins Repo und haben gleich eine externe Abhängigkeit weniger.

Ich bin für Option 2.

@mathebox: Ich hab dir das mal ganz frech zugeschoben, weil die Map ja von dir kommt. :)

**Comment by mathebox** [comment]
Okay, ich hab die aktuelle Seite auch erstmal nur als Dummy-Seite eingefügt.

**Comment by Bensk1** [comment]
Wir haben uns dafür entschieden, während der Entwicklung Option 2 zu verfolgen.
