### ISSUE TITLE
Workflow für die Verwaltung von Facebook-Seiten und Veranstaltungen optimieren

### ISSUE THREAD

**Issue by mathebox** [Strassengezwitscher/Strassengezwitscher#191]
Zurzeit gibt es nur die Standard-CRUD-Seiten. Zusammen mit @humuzz sollten wir klären, wie ein Moderationsprozess genau aussieht und mit welchen Elementen wir diesen unterstützen können.

**Comment by humuzz** [comment]
Gerne, wenn ihr mir erklärt, worum es genau geht..

**Comment by mathebox** [comment]
Gerade sind die Seiten für die Verwaltung noch sehr einfach und nicht unbedingt Nutzer-freundlich. Das können wir besser. Es geht zB darum welche Informationen in der Liste angezeigt werden sollen.
Die Funktionen sind aber erstmal da. Deshalb ist die Priorität nicht so hoch.

**Comment by mathebox** [comment]
siehe #288
