### ISSUE TITLE
User-Frontend-Config über Django ausliefern

### ISSUE THREAD

**Issue by mathebox** [Strassengezwitscher/Strassengezwitscher#196]
Damit man Keys nicht doppelt eintragen muss, könnten wir die Config für User-Frontend mit Django ausliefern (Dictionary/JS-Objekt als Template-Variabel).
In Typescript brauchen wir dann nur ein Wrapper, der das JS-Objekt im Typescript-Code verfügbar macht.

**Comment by Bensk1** [comment]
@mathebox bitte mit @piepmatz besprechen.
