### ISSUE TITLE
Kontaktformular auf Produktion System kann nicht gesendet werden

### ISSUE THREAD

**Issue by ChristopherSchmidt89** [Strassengezwitscher/Strassengezwitscher#197]
Auf dem Master im Production System, ist die Serverantwort, nach Absenden einer validen Kontaktanfrage ein 502 Bad Gateway

**Comment by piepmatz** [comment]
Notiz an mich: Das ist ein Timeout. Nach x Sekunden schießt uwsgi den Prozess ab, der den POST-Request bearbeitet, weil der noch immer nicht geantwortet hat. Nginx gibt deshalb einen 502 zurück.
Warum das Timeout auftritt, ist noch unklar.

**Comment by piepmatz** [comment]
Mh, ich hab den Django-Prozess neugestartet und die sensitive_settings.pyc gelöscht. Jetzt gehts.
