### ISSUE TITLE
Von typings auf @types (via npm) wechseln

### ISSUE THREAD

**Issue by mathebox** [Strassengezwitscher/Strassengezwitscher#199]
Ab Typscript 2.0 werden die Typ-Informationen (d.ts-Dateien) über npm ausgeliefert. Somoit brauchen wir nicht mehr typings. Allerdings sind zurzeit noch nicht alles Pakete, die wir verwenden, unterstützt.

**Comment by ChristopherSchmidt89** [comment]
Noch das Wiki aktualisieren, dann kann das Issue in Closed
