### ISSUE TITLE
Twitter-Feed-Konfiguration im Betreiberbereich

### ISSUE THREAD

**Issue by Bensk1** [Strassengezwitscher/Strassengezwitscher#217]
Im Betreiberbereich können Moderatoren zu jeder Veranstaltung die Integration des Twitter-Feeds hinzufügen. Dazu müssen folgende Einstellungen vorgenommen werden:

- Twitteraccount (einfaches Textfeld)
- Hashtags (einfaches Textfeld, Hashtags werden durch Kommata getrennt)
- Filter des Zeitraums (Tageweise genügt. Vermutlich zwei Datepicker)

**Comment by mathebox** [comment]
Brauchen wir die Möglichkeit mehrere Twitteraccounts einzutragen?

**Comment by Bensk1** [comment]
Ich habe die Spezifikation von @humuzz weitergegeben. Er hat erstmal nichts in die Richtung gefordert.

**Comment by humuzz** [comment]
Doch, bitte, wenn's geht.

**Comment by mathebox** [comment]
Ja, das ist kein Problem.
