### ISSUE TITLE
Twitter-Feed-Anzeige im Nutzerbereich

### ISSUE THREAD

**Issue by Bensk1** [Strassengezwitscher/Strassengezwitscher#218]
Die kleine Infobox über Veranstaltungen erhält einen zusätzlichen Link auf eine Detailseite zur Veranstaltunge bzw. zu einem PopOver. Dort finden sich alle Informationen zur Veranstaltung und der Twitterfeed in einfacher Form. Nothing fancy bis jetzt.

**Comment by mathebox** [comment]
Die Detailseite einer Veranstaltung soll unter `/events/:id` verfügbar sein. Es werden erstmal die gleichen Daten wie in der Infobox anggezeigt plus der Twitterfeed.
