### ISSUE TITLE
Zeitliches Filtern der Veranstaltungen

### ISSUE THREAD

**Issue by Bensk1** [Strassengezwitscher/Strassengezwitscher#225]
Aus momentaner zeitlicher Sicht soll es drei Einstellungen zum Filtern von Veranstaltungen (Facebook-Seiten haben kein Datum) geben:

- Aktuell: Gezeigt werden alle Veranstaltungen der vergangenen 30 Tage und zwar in transparentem. Weiterhin alle zukünftigen Veranstaltungen in dem Magenta-Farbton des Logos
- 2016 (aktuelles Jahr): In vollem Schwarzton werden alle bisherigen Veranstaltungen des Jahres 2016 bis heute angezeigt. Keine zukünftigen Veranstaltungen.
- 2015: In vollem Schwarzton werden alle Veranstaltungen des Jahres 2015 angezeigt.

Die  Startkonfiguration ist “aktuell”. Die Filter sind exklusiv, es kann also nur eine Einstellung gleichzeitig aktiv sein.

![ebenen](https://cloud.githubusercontent.com/assets/1655756/18580912/78e4988e-7bfe-11e6-8316-dc8a66ce5da6.png)

**Comment by humuzz** [comment]
Könntet ihr noch die Ebene 2017 hinzufügen?

**Comment by Bensk1** [comment]
Nur noch das Review, dann ist sie verfügbar.

**Comment by Bensk1** [comment]
Fertig
