### ISSUE TITLE
Initiale Anfrage der Events vom Server wird doppelt ausgeführt 

### ISSUE THREAD

**Issue by Bensk1** [Strassengezwitscher/Strassengezwitscher#227]

**Comment by ChristopherSchmidt89** [comment]
Meinst du doppelte erhalten der `events.json` was aus dem Call der `retrieveVisibleMapObjects`  
sowohl aus  `ngAfterViewInit`  
als auch aus  `onCheckboxChange`  ( da beim Initialisieren der MapObjectSettings der Events die visibility auf `true` gesetzt wird, wird ein ngModelChange getriggert )
beim Erstellen der Komponente resultiert.

Falls ja würde ich vorschlagen den `retrieveVisibleMapObjects` aus dem ngAfterViewInit rauszunehmen.

**Comment by Bensk1** [comment]
Genau das meine ich. Ist wohl momentan der einzige Weg, wenn auch nicht der schönste.
