### ISSUE TITLE
Twitter-API anfragen und für Nutzerbereich bereitstellen

### ISSUE THREAD

**Issue by mathebox** [Strassengezwitscher/Strassengezwitscher#230]
Twitter-API soll angefragt werden und dann an den Nutzerbereich weitergeben werden.

**Comment by piepmatz** [comment]
Notizen an mich: Um Rate Limits zu beachten, empfiehlt Twitter das Caching von Antworten. Das beachten wir in einer ersten Version noch nicht.
Die Twitter-API verlangt eine Authentifizierung, wir haben einen Test-Account erstellt.
Wir nutzen die REST-API über einen Python-Wrapper namens TwitterAPI, suchen entsprechend der Kriterien nach Tweets.
Wir geben den Inhalt der gefundenen Tweets nicht direkt ans Frontend zurück, sondern eine Liste aus Dicts. Jedes Dict entspricht einem Tweet. Felder sind username, date (als epoch zum Sortieren) und die ID des Tweets.
Daraus kann das Frontend die Tweets nett abfragen, ohne Rate Limit.

**Comment by mathebox** [comment]
Die Authentifizierung für die Twitter-API kann (und sollte irgendwie auch) über den offiziellen Streetcoverage-Twitter-Account laufen.

@humuzz Könntest du bitte zwei Access Token für uns generieren? Einmal für die dev-Version und einmal für die Seite, die online ist. Genau gesagt benötigen wir:
- 1x consumer_key
- 1x consumer_secret
- 2x access_token_key
- 2x access_token_secret

Hier ist eine Anleitung: https://dev.twitter.com/oauth/overview/application-owner-access-tokens

@piepmatz Sind die Names so richtig? Kannst du die gegebenenfalls anpassen?

**Comment by humuzz** [comment]
Habe ich dir zukommen lassen. Ich weiß nicht, ob es von Bedeutung ist, aber bei unserem Account handelt es sich um einen verifizierten Account. Wenn wir uns von anderen Geräten einloggen wollen, müssen wir das über unser Hauptgerät bestätigen. Ich hoffe, das macht für die Authentifizierung der Twitter-API keine Probleme.

**Comment by mathebox** [comment]
@piepmatz Im Angular-Teil benötige ich nur die `id` vom Tweet (und nicht noch den `username`). Wenn wir davon ausgehen, dass der Server die Tweet-Ids in der chronologisch richtigen Reihenfolge schickt, braucht `date` auch nicht an Angular weitergeben werden.

**Comment by piepmatz** [comment]
Ok, `username` nehm ich raus.
`search/tweets` antwortet chronologisch, das neuste zuerst. Wenn wir später aber diesen Mix aus REST API und Streaming API haben, kann da schon leicht was durcheinander gehen. Von daher würde dir `date` schon mitschicken, du musst es ja (noch?) nicht benutzen. Oder ich kommentiere die eine Zeile einfach aus.

**Comment by mathebox** [comment]
Was kann da durcheinander gehen? In Angular halte ich ein Array von tweetIds. Eine neue Id wird mit `prepend` hinzugefügt. Falls mal zwei Tweets recht zeitgleich erstellt werden und sie in umgedrehter Reihenfolge erscheinen, find ich das nicht schlimm.
