### ISSUE TITLE
MapObjects auf Karten anzeigen

### ISSUE THREAD

**Issue by Bensk1** [Strassengezwitscher/Strassengezwitscher#24]
Zunächst müssen [MapObjects](https://github.com/Strassengezwitscher/Strassengezwitscher/wiki/Data-Models), mit Hilfe der Google-Maps-API als Pins auf die Karte gezeichnet werden.

Ein reiner Frontend-Task. Backend-Funktionalität wird noch nicht benötigt, es kann mit Mocks gearbeitet werden. Natürlich sollte es so implementiert werden, dass der Server mit seiner API nur noch "angeschlossen werden muss."

**Comment by mathebox** [comment]
Zusätzlich kann man sich gleich noch angucken wie man die MapObjects gut clustern könnte. https://developers.google.com/maps/articles/toomanymarkers
