### ISSUE TITLE
Textanhänge mit Umlauten führen zu Exception

### ISSUE THREAD

**Issue by piepmatz** [Strassengezwitscher/Strassengezwitscher#267]
Python 2 und Unicode ist ein Krampf...

Bug lässt sich triggern mit: Kontaktformular, Textdatei als Anhang wählen, diese muss Umlaut enthalten.

Die mit Abstand einfachste Lösung wäre, auf Python 3 umzusteigen, da läuft sowas nämlich wie geschmiert.

**Comment by Bensk1** [comment]
Alle Tests laufen auf Python 3 oder? Aber vermutlich müssten wir das Produkt als Ganzes vorher irgendwo testen und nicht nur lokal?

Sent from mobile.

**Comment by piepmatz** [comment]
Ja, alles läuft unter Python 3, Travis prüft gegen 2.7, 3.4 und 3.5.
Wir sollten das mal besprechen, welche Python-Version wir nehmen wollen. Wir haben hier ja kein Legacyprodukt, das 2.7 noch unterstützen muss, sondern sind in der glücklichen Lage, die Verbesserungen in 3 nutzen zu können. Vielleicht sollten wir genau das tun. 
Ich könnte ja mal den deployten Develop-Branch unter 3 laufen lassen.

**Comment by Bensk1** [comment]
Guter Vorschlag! Ne Idee für nen hotfix für die Umlaute momentan?

Sent from mobile.

**Comment by piepmatz** [comment]
Ich spiel mit der Fehlerstelle mal etwas rum. Ob ich heute dazu noch Zeit finde, weiß ich nicht. Eigentlich sollte sich da ja auch in 2.7 ne vernünftige Lösung finden lassen. Aber in 3 ist das eben sehr viel bequemer.
Bis dahin sollten lieber nur Binärdaten verschickt werden. :)
