### ISSUE TITLE
Kontaktformular: Fehler JSON.parse

### ISSUE THREAD

**Issue by mathebox** [Strassengezwitscher/Strassengezwitscher#272]
Mit Firefox unter OS X bekommt man folgende Fehlermeldung:

```
JSON.parse: unexpected character at line 5 column 1 of the JSON data
```
wenn man:
- erst den Recaptcha anklickt
- dann in ein Feld (Betreff oder Nachricht) klickt

Der Senden-Button wird auch nicht freigeschaltet.

**Comment by Bensk1** [comment]
Kann ich nicht reproduzieren. Welche Firefox Version?

**Comment by piepmatz** [comment]
Habe ich auch nicht reproduzieren können.

**Comment by mathebox** [comment]
FF 49 aber nur im dev mode.
