### ISSUE TITLE
Legende zur Karte hinzufügen

### ISSUE THREAD

**Issue by roschaefer** [Strassengezwitscher/Strassengezwitscher#277]
Ich habe ca. 5 Minuten darüber nachgedacht, was die Transparenz wohl bedeuten mag und es bis jetzt nicht verstanden.

Es gibt ein Sprichwort dazu "Don't make me think".

**Comment by roschaefer** [comment]
Ahhhh, vergangene und kommende Veranstaltungen! Dafür sollte es wenigstens eine Legende geben. Und warum sind Veranstaltungen der Jahre 2015 und 2016 dann schwarz? Ist das nicht inkonsistent? Macht Veranstaltungen in den letzten 30 Tagen doch auch einfach schwarz.

**Comment by humuzz** [comment]
Bin auch dafür, die vergangenen Veranstaltungen immer schwarz zu machen (das mit verblassend, je älter, finde ich dennoch gut). Ich würde nur die zukünftigen rot einfärben.

**Comment by Bensk1** [comment]
Aufgegangen in #292 und #290
