### ISSUE TITLE
Facebook Seiten per default anzeigen

### ISSUE THREAD

**Issue by roschaefer** [Strassengezwitscher/Strassengezwitscher#278]
Wenn ich als Nutzer die Seite das erste Mal sehe, möchte ich
dass die Facebook Seiten per default auf der Karte sichtbar sind
denn das sind Inhalte. Es stört nicht wenn die Karte etwas voller ist, im Gegenteil. Mehr Inhalte!

**Comment by mathebox** [comment]
Wurde von den Straßengezwitscher-Jungs so gefordert. Aber @humuzz was denkst du?

**Comment by humuzz** [comment]
Ja, stimmt schon, wäre nicht verkehrt. Macht meiner Meinung aber nur Sinn, wenn wir die Gruppierung hinbekommen. Sonst liegen da ja noch mehr Icons übereinander, Auswählen wir dann noch schwieriger.

**Comment by Bensk1** [comment]
Abhängig von #291
