### ISSUE TITLE
Kontaktformular: Anhänge werden bei weiterer Nachricht nicht resetted

### ISSUE THREAD

**Issue by piepmatz** [Strassengezwitscher/Strassengezwitscher#281]
Nutzt man die in der Erfolgsmeldung nach dem Absenden des Kontaktformulars angebotene Möglichkeit, eine weitere Nachricht zu senden, so sind zuvor versendete Anhänge bei der neuen Nachricht bereits ausgewählt.

**Comment by ChristopherSchmidt89** [comment]
Ist das in einer speziellen Browser-Konstellation aufgetreten oder generell ?
