### ISSUE TITLE
Einrichtung von Mattermost (group communication)

### ISSUE THREAD

**Issue by Bensk1** [Strassengezwitscher/Strassengezwitscher#3]

**Comment by tgraupne** [comment]
Hi Leute,

ich bin Tom aus Dresden und wie ihr vielleicht/vielleicht aber auch noch nicht wisst, werde ich von hier aus am Projekt mitarbeiten. Da wir noch keine gemeinsame Kommunikationsplattform haben, möchte ich hier mal kurz 'Hallo' sagen :-)

Wenn ich mir die bestehenden Issues so anschaue, dann scheint es, dass ihr Projekt-Kickoff und Planung schon abgeschlossen habt. Anforderungen definiert sind und so weiter....

Ich würde mich sehr freuen, wenn ihr mich hier irgendwie abholen könntet.

Viele Grüße,

Tom

**Comment by Bensk1** [comment]
Keine Sorge Tom, die Projektplanung ist noch längst nicht abgeschlossen, wir möchten das Projekt iterativ angehen, es werden noch viele Issues hinzukommen und auch viele Anforderungen werden noch definiert werden müssen
