### ISSUE TITLE
Genauigkeit für MapObjects erhöhen

### ISSUE THREAD

**Issue by mathebox** [Strassengezwitscher/Strassengezwitscher#308]
Anstatt 6 sollen 7 Nachkommastellen für `location_lat` und `location_long` benutzt werden. Das entspricht der Genauigkeit von Google Maps.

**Comment by piepmatz** [comment]
Überschlagen siehts aus, als würden wir damit die maximale Fehlabweichung von knapp 30 cm auf knapp 3 cm reduzieren. Darauf sollte es nun eigentlich nicht ankommen. Oder was ist deine Motivation?

**Comment by mathebox** [comment]
Die Koordinaten bei Google Maps werden mit 7 Nachkommastellen angegeben. So bräuchte man nur die Koordinaten kopieren. (siehe Mattermost)

**Comment by humuzz** [comment]
Ne, passt schon hab nur von der falschen Stelle kopiert!
