### ISSUE TITLE
Anmerkungen an MapObjects ermöglichen

### ISSUE THREAD

**Issue by piepmatz** [Strassengezwitscher/Strassengezwitscher#324]
Gewünscht ist ein Feld, in das Anmerkungen zur internen Benutzung gespeichert werden können.
Der Inhalt soll also nicht über die API ausgeliefert werden, sondern lediglich im Betreiberbereich verfügbar sein.

**Comment by mathebox** [comment]
@piepmatz @Bensk1 Designentscheidung:
Als Attribute an `MapObject` oder an den Subklassen?

**Comment by piepmatz** [comment]
MapObject.
Was spricht für die Subklassen? Falls es mal weitere Subklassen geben sollte, die keine Anmerkungen benötigen?

**Comment by Bensk1** [comment]
Hätte intuitiv auch `MapObject` gesagt.

**Comment by mathebox** [comment]
Gerade haben sowohl `Event` als auch `FacebookPage` ein `notes`-Attribute. Das würde ich dann auch in `MapObject` ziehen.
