### ISSUE TITLE
Python 2 Support entfernen

### ISSUE THREAD

**Issue by piepmatz** [Strassengezwitscher/Strassengezwitscher#329]
- [ ] remove `@python_2_unicode_compatible`
- [ ] use `unittest.mock`

**Comment by mathebox** [comment]
und 3.6 hinzufügen?

**Comment by mathebox** [comment]
dann können wir auch `unittest.mock` benutzen anstatt `mock` (see https://github.com/Strassengezwitscher/Strassengezwitscher/blob/develop/requirements/dev.txt#L5)
