### ISSUE TITLE
Zustellung von (verschlüsselten) Nachrichten des Kontaktformulars

### ISSUE THREAD

**Issue by piepmatz** [Strassengezwitscher/Strassengezwitscher#47]
Ihr möchtet verschlüsselte Nachrichten.

Die Daten des Kontaktformulars werden ohnehin per TLS verschlüsselt zum Server übertragen. Wenn wir sie dort speichern, sind sie jedoch unverschlüsselt. Das wäre die Minimalvariante.

Schöner wäre PGP, wie von euch vorgeschlagen. Auch diese Verschlüsselung kriegen wir hin.
Deutlich schwieriger wird aber die Entschlüsselung, wenn ihr die Nachrichten des Kontaktformulars im Betreiber-/Adminbereich einsehen wollt. PGP im Browser ist nämlich recht umständlich und erfordert ein Browserplugin. Die momentan beste Lösung in dieser Richtung scheint [Mailvelope](https://www.mailvelope.com/) zu sein, von der auch gmx, web.de und posteo für ihre Webmailer Gebrauch machen.
Wenn ihr das zwingend alles im Browser machen wollt, können wir uns das anschauen, aber die meines Erachtens nach für alle einfachere Variante ist, dass ihr per GPG verschlüsselte Nachrichten per Mail zugestellt bekommt und dann ganz normal dort entschlüsselt.

Wenn wir das so machen, dass verschlüsselte Nachrichten per Mail an euch gehen, dann führt es zu Verwirrung, falls unverschlüsselte Nachrichten über den Betreiber-/Adminbereich eingesehen werden können. Das würde ich eher einheitlich halten wollen und einen Kanal für alle Kontaktanfragen/Nachrichten nutzen, also Email an euch.

Wir sind bislang davon ausgegangen, dass wir Nachrichten auf dem Server speichern. Wenn wir das so handhaben wie oben vorgeschlagen, ist diese serverseitige Speicherung unnötig.
Um an der Kontaktfunktionalität weiterzubauen, brauchen wir also euer Feedback, ob wir das so umsetzen sollen wie hier vorgeschlagen oder eben anders.

**Comment by Bensk1** [comment]
Darüber hatten wir ja bei unserem Treffen in der Mensa kurz gesprochen. Matze hat auf jeden Fall Recht, es bietet sich an, Euch verschlüsselte Nachrichten per Mail zukommen zu lassen.

**Comment by humuzz** [comment]
Ja, dann machen wir es so, dass die Nachrichten PGP-verschlüsselt per Mail an uns gehen. PGP-versiert bin ich, du hast recht, Browser-PGP funzt nicht immer super, im Linux gibt's z.B. kein Mailvelope-Plugin für Firefox. Dann können wir vielleicht die Trennung PGP-verschlüsselt/PGP-unverschlüsselt ja über unterschiedliche Mail-Adressen machen? Dann verzichten wir auf die Browser-Lösung.

**Comment by Bensk1** [comment]
Wir könnten ja schon alle Nachrichten an Euch mit PGP verschlüsseln. Unverschlüsselte können wir eigentlich komplett vermeiden. Nur Eure Antwort an den Absender muss eventuell unverschlüsselt laufen.

**Comment by piepmatz** [comment]
Richtig, es stellt sich nämlich die Frage, wann verschlüsselt wird und wann nicht. Verschlüsselung aller Nachrichten ist für uns sogar einfacher. Ansonsten sind unterschiedliche Empfängeradressen aber auch möglich.
Wir könnten im Kontaktformular ja explizit angeben, dass ein PGP Public Key mitgeschickt werden soll, falls eine verschlüsselte Antwort erwünscht ist.

**Comment by Bensk1** [comment]
Halte ich für die beste Möglichkeit, so würde ich mir das auch vorstellen.

**Comment by humuzz** [comment]
An sich würde ich sagen, dann verschlüsseln wir alles, aber das geht nur mit zwei verschiedenen PGP-Keys, da es Mails gibt, die nur wenige bzw. wir Admins lesen dürfen (vertrauliche Dokumente etc.) und Anfragen, die vielleicht ein einer erweiterten Personengruppe bearbeitet werden (allgemeine Anfragen..). Die Angabe, dass bei gewünschter Antwort der eigene PGP Key mitgeschickt werden soll, finde ich sinnvoll.

**Comment by piepmatz** [comment]
Das ist eine Möglichkeit, dass die Admins sich einen GPG-Key teilen und die Moderatoren ebenfalls.
Alternativ, und etwas sicherer, kann jeder Admin/Moderator seinen PGP Key hinterlegen und bekommt eine Mail, die nur er lesen kann.

Jetzt habe ich aber noch nicht ganz verstanden, anhand welcher Kriterien entschieden wird, ob eine Nachricht nur an die Admins geht oder auch bzw. ausschließlich an die Moderatoren.
Es gibt da das Kontaktformular, zu dem es auch einen Betreff gibt. Ist dieser Betreff vom Nutzer frei wählbar? Oder gibt es nur einige zur Auswahl anhand derer diese Entscheidung fällt? Wie habt ihr euch das gedacht?

**Comment by humuzz** [comment]
In der Projektskizze habe ich die Unterschiedlichen Kontaktmöglichkeiten "Kontakt(formular)", "Kontakt(formular) für Journalisten", "Button: „Mitmachen“" und "Button: „Hinweise“". Die letzte Kontaktaufnahmemöglichkeit ist die sensibelste, hier sollte GPG verschlüsselt werden und nur die Admins Kontakt haben. Hier würde ich vorschlagen, dass "Hinweise" also an eine Adresse à la blackbox@strassengezwitscher.de geht. Alles andere kann dann mit unterschiedlichen Betreffzeilen an eine allgemeine Mail-Adresse gehen, sei es info@strassengezwitscher.de oder eine neue. Den PGP-Key teilen sich dann alle, die auf die Mail-Adresse Zugriff haben. Dass jeder Admin/Moderator seinen Key hinterlegt, finde ich zu aufwändig bzw. da fehlen mir die Kenntnisse. Können für eine mail-Adresse mehrere Schlüssel generiert werden?

Zu deinem zweiten Absatz: Ich finde, ein Kontaktformular mit festgelegten Betreffzeilen (von den o.g. vier Möglichkeiten) zur Auswahl klingt nach einer vernünftigen Lösung. Frei wählbar muss nicht sein oder kann eine zusätzliche Möglichkeit sein, in etwa "Sonstiges".

**Comment by piepmatz** [comment]
Kontaktformular, Kontaktformular für Journalisten, Mitmachen und Hinweise - alles soll zum Kontaktformular führen?

> Können für eine mail-Adresse mehrere Schlüssel generiert werden?

Mh. Können schon. Dein Mailprogramm weiß ja, zu welcher Empfängeradresse es einen Schlüssel gibt. Wird nun eine Mail an einen solchem Empfänger geschrieben, wird dessen Public Key zum Verschlüsseln genutzt. Wenn es aber mehrere Keys für ein und dieselbe Adresse geben soll, dann wird das für einen Menschen schon kompliziert und ich kann mir vorstellen, dass die Programme dann auch nicht wissen, welchen Key sie nehmen sollen.
Ich habe das dennoch gerade mal am Mac ausprobiert (MacGPG + Apple Mail) und da wurde die Nachricht mit allen vorhandenen Schlüsseln für diese Adresse verschlüsselt, sodass jeder Empfänger entschlüsseln konnte. So soll es sein. Ab das mit anderen Mailprogrammen auch funktioniert, weiß ich nicht.

Ich sehe letztlich zwei Möglichkeiten:
- Es gibt nur 1 Schlüsselpaar, das alle berechtigten Empfänger besitzen und sich teilen. Da ist die Schlüsselpflege einfacher, dafür risikoreicher wegen größerer Angriffsfläche. Geht einem Nutzer der Schlüssel/Rechner verloren, müssen alle berechtigten Empfänger den neu anzulegenden Schlüssel einrichten.
- Jeder berechtigte Empfänger hat ein eigenes Schlüsselpaar für die geteilte Adresse (z.B. blackbox@). Die Schlüsselpflege ist aufwändiger und potentiell unübersichtlicher. Bei Schlüsselverlust muss nur der Betroffene Empfänger einen neuen Schlüssel anlegen. Hier müsste wie oben beschrieben geprüft werden, ob andere Mailprogramme klar kommen mit mehreren Schlüsseln pro Empfänger (je länger ich drüber nachdenke, desto eher gehe ich davon aus).

In beiden Fällen müssen wir eine Möglichkeiten bauen, den bzw. die Public Keys auf der Platform zu hinterlegen. Letztlich wird also doch entweder jeder User seinen Public Key hinterlegen oder aber für jede Empfängeradresse wird der Public Key hinterlegt. Hinterlegen ist letztlich nichts anderes, als den Public Key einmalig nach dem Einloggen auf der Platform in ein Textfeld einzutragen, also nicht aufwändig.

Welche Variante ist euch lieber?

**Comment by humuzz** [comment]
Ja, das können wir so lösen, dass alles ein Kontaktformular ist. Nur nicht "Seite eintragen" und "Event eintragen", hier werden ja weitere Felder benötigt.

Ich würde sagen, dass wir zwei Empfängeradressen anlegen, z.B.
- blackbox@ für Hinweise und
- income@ für alles andere. 

Jede dieser beiden Empfängeradressen hat dann jeweils einen Public Key, den sich dann jeweils unterschiedlich viele Leute teilen. Die Unterscheidung je nach Art der Kontaktanfrage unterscheiden wir je nach Betreff. Wenn ich das richtig verstanden habe, ist das Variante 1.

**Comment by piepmatz** [comment]
Ok, machen wir so.
Bloß income@ vermutlich nicht, das klingt doch sehr Einkommen/Lohn. Vielleicht eher info@ oder inbox@?

**Comment by humuzz** [comment]
Ja, das hast Du wohl recht. Da info@ schon vergehen ist, eher inbox@.

**Comment by Bensk1** [comment]
Wäre dann soweit geklärt? In kleinere Tasks verpacken und implementieren?

**Comment by mathebox** [comment]
Könnte man nicht auch die Funktionalität einbauen, das man die Email-Adressen im Adminbereich definieren und notfalls ändern kann?

**Comment by Bensk1** [comment]
Könnte man, aber wir wollen den Aufwand insgesamt ja möglichst gering halten.
