### ISSUE TITLE
Events und FacebookPages aus Excel in Datenbank laden

### ISSUE THREAD

**Issue by piepmatz** [Strassengezwitscher/Strassengezwitscher#49]
Es gibt im Drive Excel- und CSV-Dateien für Events und FacebookPages, für die wir Fixtures erstellen können, damit die bereits vorhandene Datenbasis auch auf der Platform vorhanden ist.

**Comment by piepmatz** [comment]
@humuzz: Wir müssen mal abklären, was von den Daten aus den Excel- und CSV-Dateien auch in der Datenbank laden soll. Konkret also, welche Spalten auch in der Datenbank vorhanden sein sollen.

Momentan gibt es da ein paar Unstimmigkeiten zwischen den Angaben in der Projektskizze und den Spalten in den Excel-Dokumenten.

Beginnen wir mit Unklarheiten zu Veranstaltungen:
- Mobilisierung: Projektskizze Seite 3. Ist das eine eigene Spalte oder gehört das zu `Veranstalter`? Was ist damit gemeint?
- Veranstaltungsort: In Excel enthalten. Ist eine separate Spalte zusätzlich zu `Ort`.
- Teilnehmerzahl: In Excel enthalten.
- Versammlung?: In Excel enthalten.
- Ansammlung?: In Excel enthalten.

Was davon soll auch in der Datenbank vorhanden sein?
@mathebox: Wir haben momentan ein Feld `type` fürs Event-Model. Wofür ist das gedacht?

Und zu den Unklarheiten zu Facebook-Seiten:
- Beschreibung: Taucht in der Projektskizze zusätzlich zu `Name` auf, benutzt ihr aber nicht in den Excel-Dateien.
- Postingfrequenz: In Excel enthalten.
- Anmerkungen: In Excel enthalten.
- Zeitpunkt des Erscheinens: In Excel enthalten. Was ist damit gemeint?
- Zeitpunkt der Eintragung: In Excel enthalten. Was ist damit gemeint?

Auch hier wieder: Was davon soll auch in der Datenbank vorhanden sein?

Zusätzlich noch zwei Fragen?
- Die Excel-Files enthalten ja schon rudimentäre Like-Statistiken, also zu welchem Datum es wie viele Likes gab. Sollen wir die in die Datenbank übernehmen oder soll die Platform mit Inbetriebnahme anfangen, Werte aufzuzeichnen?
- Gibts es einen Grund, dass es für die Veranstaltungen sowohl eine Excel- als auch eine CSV-Datei gibt? Gibt es vielleicht gar Unterschiede zwischen beiden?

**Comment by humuzz** [comment]
Morgen antworte ich ausführlicher, erst einmal auf die zwei zusätzlichen Fragen: Ja, Statistikdaten übernehmen und nein, es gibt keinen Unterschied zwischen Excel und csv-Datei.

**Comment by Bensk1** [comment]
Dazu hatte mir Alexej zusätzliche Informationen gegeben. Die kann ich auch noch einpflegen.

**Comment by humuzz** [comment]
_Unklarheiten zu Veranstaltungen:_

_Mobilisierung: Projektskizze Seite 3. Ist das eine eigene Spalte oder gehört das zu Veranstalter? Was ist damit gemeint?_ **-> Das gehört zusammen. Nicht immer gibt es einen klaren Organisator/Demoanmelder. Manchmal mobilsiert einfach nur eine FB-Seite, daher unterschiedliche Bezeichnungen.**

_Veranstaltungsort: In Excel enthalten. Ist eine separate Spalte zusätzlich zu Ort._ **-> Im Idealfall ist die Spalte "Veranstaltungsort" eine präzisere Beschreibung von "Ort". Wenn es möglich ist, dann beide Spalten durch Kommata getrennt in dem Feld "Zeit/Ort" anzeigen.**

_Teilnehmerzahl: In Excel enthalten._ **-> Das ist eine Information, die erst während oder nach einer Kundgebung zu erfassen ist. In der Info-Box muss sie daher nicht angezeigt werden. Vielmehr auf der Veranstaltungsseite, auf der alle möglichen Informationen rund im die Kundgebung gesammelt werden.**

_Versammlung?: In Excel enthalten.
Ansammlung?: In Excel enthalten._
**-> Beide Spalten sind interessante Informationen (Versammlungen sind angemeldete Demos, Ansammlungen nicht), jedoch haben wir hier zuwenig Informationen für 2016, sodass die Information nicht angezeigt werden muss.**

**In der Datenbank sollte so viel wie möglich (am besten alle Spalten) vorhanden sein. Die Frage ist nur, was angezeigt werden soll. In der Projektskizze S. 6 ist von Status-Check-Button die Rede. Ist zwar optional für einzelne Informationen, aber könnte man so könnte man das für solche Informationen wie Ansammlung/Versammlung nutzen. Ansonsten wird dies eben manuell auf der Veranstaltungsseite eingetragen.**

_Unklarheiten zu Facebook-Seiten:_

_Beschreibung: Taucht in der Projektskizze zusätzlich zu Name auf, benutzt ihr aber nicht in den Excel-Dateien._ **-> "Anzeige-Name" (Projektskizze) = "Bezeichnung" (Excel). Du hast Recht, die Information zu "Beschreibung", wie in der Projektskizze S. 3 beschrieben, fehlt. Das entspräche dann der Spalte "Anmerkungen" im Excel und kann dann mit "Posting-Frequenz" zusammenfallen. Die Info ist dann nicht öffentlich.**
_Postingfrequenz: In Excel enthalten._ **-> die Spalte ist nicht überall ausgefüllt, dieses Feld kann man weglassen bzw. können wir später durch andere Information ersetzen oder die Informationen ebenfalls unter "Anmerkungen" bzw. "Beschreibung" speichern. Am besten letzteres. Nicht öffentlich.**
_Anmerkungen: In Excel enthalten._ **-> s. oben**
Zeitpunkt des Erscheinens: In Excel enthalten. Was ist damit gemeint? **-> Sollte für interne Zwecke gespeichert werden, möglicherweise auch unter "Anmerkungen" bzw. "Beschreibung".**
Zeitpunkt der Eintragung: In Excel enthalten. Was ist damit gemeint? **-> Sollte für interne Zwecke gespeichert werden, möglicherweise auch unter "Anmerkungen" bzw. "Beschreibung".**

**Wie ihr seht ist das Feld "Anmerkungen" bzw. "Beschreibung" ein Sammelfeld für alle Informationen, die sonst nirgends hinpassen.**

**Comment by piepmatz** [comment]
@humuzz wir haben jetzt eure Daten aus den Excel-Tabellen in die Datenbank übernommen. Ihr werdet ja vermutlich diese Tabellen auch vorerst weiterhin benutzen, solange die Platform noch nicht fertig ist. Ich würde euch daher empfehlen, eure zukünftigen Eintragungen in den Tabellen besonders zu kennzeichnen, dass ihr die später auf der Platform nachtragen könnt.

Während es in den Excel-Tabellen noch keine Zuordnung zwischen Facebook-Seiten und Veranstaltungen gab, soll diese Verknüpfung auf der Platform natürlich vorhanden sein.
In den jetzigen Daten haben wir das wie folgt gemacht: Wenn der Organisator einer Veranstaltung identisch ist mit dem Namen einer Facebook-Seite, dann haben wir die Veranstaltung der Seite zugeordnet. Groß- und Kleinschreibung haben wir dabei ignoriert. Ist dieses Vorgehen so richtig?

**Comment by humuzz** [comment]
An sich ja. Das Problem ist, dass sich die Seiten einfach umbenennen können, nur die FB-ID bleibt gleich. 

Super. Wir sollten in den nächsten Tagen auch die Excel-Tabelle mit den Versammlungen 2016 fertig haben.
