### ISSUE TITLE
Kontaktmöglichkeit: Eingabe-Maske für Nachricht an Betreiber bauen

### ISSUE THREAD

**Issue by piepmatz** [Strassengezwitscher/Strassengezwitscher#58]
Im User Frontend gibt es diverse Möglichkeiten, in Kontakt mit den Betreibern zu treten:
Kontaktformular, Kontaktformular für Journalisten, Mitmachen und Hinweise (siehe Projektskizze) - ein Klick auf einen dieser Links führt zum Kontaktformular.

Für die eingegebenen Daten bietet sich clientseitige Validierung ein. Die validen Daten werden anschließend an einen API-Endpoint geschickt. Infos dazu werden nachgereicht, siehe auch #59. Um Verschlüsselung muss sich an dieser Stelle keine Gedanken gemacht werden.

@ChristopherSchmidt89: Ist es ok, dass ich dir das zur Einarbeitung in Angular zugeschoben habe?

Die ursprüngliche Diskussion zum Thema befindet sich in #47.

**Comment by Bensk1** [comment]
Nur zum Verständnis: Im Backend findet aber eine nochmalige Validierung statt, da diese im Frontend ja umgangen werden kann?

**Comment by piepmatz** [comment]
@Bensk1: Ja, das wird höchstwahrscheinlich nötig sein.

**Comment by piepmatz** [comment]
Nachrichten schicken kann jeder Nutzer, ohne angemeldet zu sein, also auch jeder Bot. Wir sollten also etwas zur Spamvermeidung einbauen, sprich ein Captcha o.Ä.

**Comment by mathebox** [comment]
Die Captcha-Idee find ich gut.
Um @Bensk1's Kommentar aus #60 aufzugreifen: client-seitige Validierung würde ich auch als reines UX-Features sehen. Zum Beispiel sollte es vermieden werden Nachrichten ohne Text zusenden.
