### ISSUE TITLE
Kontaktmöglichkeit: Spezifikation eines API-Endpoint zur Annahme von Nachrichten an die Betreiber

### ISSUE THREAD

**Issue by piepmatz** [Strassengezwitscher/Strassengezwitscher#59]
Überlegt werden muss u.a.
- wie zwischen den verschiedenen Nachrichtentypen zu unterscheiden ist. "Hinweise" gelten als besonders sensibel und werden an eine andere Emailadresse geschickt als sonstige Nachrichten.

Die ursprüngliche Diskussion zum Thema befindet sich in #47.

**Comment by piepmatz** [comment]
Da @ChristopherSchmidt89 wohl anfängt, an der #58 zu arbeiten, hier ein vorläufiger Vorschlag:
- Die Daten sollen gePOSTed werden.
- Endpoint-URL: `/contact`
- Die Daten werden *nicht* als JSON übertragen, sondern als `multipart/form-data`.
- Folgende Felder werden erwartet:
  - `name`: Name des Absenders, optional, 50 Zeichen max.
  - `email`: Emailadresse des Absenders, optional
  - `subject`: Betreff
  - `message`: Nachricht
  - `journalist`: Boolean, ob der Absender sagt, er sei Journalist, optional
  - `confidential`: Boolean, ob die Nachricht vertraulich sein soll, optional
  - `file`: Dateianhang, optional, Dateiname max. 50 Zeichen lang

Hier beispielhaft ein recht minimales HTML-Form, das ich lokal nutze:
```html
<form enctype="multipart/form-data" action="/contact" method="post">
    <table>
        <tr>
            <th><label for="id_name">Name:</label></th>
            <td><input id="id_name" maxlength="50" name="name" type="text" /></td>
        </tr>
        <tr>
            <th><label for="id_email">Email:</label></th>
            <td><input id="id_email" name="email" type="email" /></td>
        </tr>
        <tr>
            <th><label for="id_subject">Subject:</label></th>
            <td><input id="id_subject" name="subject" type="text" /></td>
        </tr>
        <tr>
            <th><label for="id_message">Message:</label></th>
            <td><textarea cols="40" id="id_message" name="message" rows="10"></textarea></td>
        </tr>
        <tr>
            <th><label for="id_journalist">Journalist:</label></th>
            <td><input id="id_journalist" name="journalist" type="checkbox" /></td>
        </tr>
        <tr>
            <th><label for="id_confidential">Confidential:</label></th>
            <td><input id="id_confidential" name="confidential" type="checkbox" /></td>
        </tr>
        <tr>
            <th><label for="id_file">File:</label></th>
            <td><input id="id_file" name="file" type="file" /></td>
        </tr>
    </table>
    <input type="submit" value="Submit">
</form>
```

**Comment by Bensk1** [comment]
+1

**Comment by piepmatz** [comment]
Habe oben die Endpoint-URL angepasst und ein Feld umbenannt: aus `file` wurde `files`, weil wir auch mehrere Anhänge unterstützen.

Was bislang noch gefehlt hat, sind die zu erwartenden Antworten.
Der Endpoint returned eine JSON-Antwort, im Header gibts also `Content-Type: application/json`.
Jede Antwort hat ein `status` Feld.

Geht alles glatt, sieht die Antwort aus wie folgt:
```json
{
    "status": "success"
}
```
_HTTP Status Code: 200_

Wenn etwas schief geht, ist der Wert von `status` immer `error`. Es gibt dann zusätzlich ein `errors` Feld mit weiteren Infos.

Wurden invalide Daten abgeschickt, z.B. das Pflicht-Feld `message` wurde nicht ausgefüllt, sieht die Antwort aus wie folgt:
```json
{
    "status": "error",
    "errors": {
        "message": [
            "This field is required."
        ]
    }
}
```
_HTTP Status Code: 400_
Zu sehen ist also, dass in `errors` das fehlerhafte Feld benannt ist und eine Liste der Fehler für dieses Feld folgt.

Ist intern irgendwas gekaputt, sodass die Mail nicht gesendet werden konnte, gibts folgende Antwort:
```json
{
    "status": "error",
    "errors": "Email could not be sent."
}
```
_HTTP Status Code: 500_
