### ISSUE TITLE
Kontaktmöglichkeit: Implementierung des API-Endpoint zur Annahme von Nachrichten an die Betreiber

### ISSUE THREAD

**Issue by piepmatz** [Strassengezwitscher/Strassengezwitscher#60]
Spezifikation in #59.
Einige Einzelschritte:
- Überlegen inwieweit die eingehenden Daten validiert werden müssen (das passiert bereits clientseitig). Ist der Validierung durch Angular zu trauen (s. auch #58)? Vermutlich nicht.
- Die eigentlich Mailanbindung bauen
    - Die zu verwendenden Empfänger-Emailadressen und PGP-Keys sind vorerst in den Settings gut aufgehoben, bis es dafür eine UI im Betreiberbereich gibt.
    - Welchen Mailprovider nehmen wir? @bensk1: Den von den Mattermost-Notifications womöglich?

Die ursprüngliche Diskussion zum Thema befindet sich in #47.

**Comment by Bensk1** [comment]
Validierung durch JavaScript ist meiner Meinung nach niemals zu trauen, weil das Javascript praktisch immer verändert werden kann. 

Der Mailprovider von den Mattermost-Notifications ist der Standard-Mailserver des Projekts. Das halte ich für die momentan beste Lösung und kostengünstigste Lösung.
