### ISSUE TITLE
Settings.py auf mehrere Dateien aufteilen

### ISSUE THREAD

**Issue by mathebox** [Strassengezwitscher/Strassengezwitscher#79]
Dann haben wir eine `settings_dev.py` und eine `settings_prod.py`. Letztere importiert alles aus `settings_dev.py`, setzt production settings, die auf github können (zb render engine vom rest framework | alles aus dem else-Zweig von “if DEBUG”), und importiert dann noch alles aus `localsettings.py`.

`settings_dev.py` sollte der Standard sein.

Siehe zweiter Ansatz: http://www.sparklewise.com/django-settings-for-production-and-development-best-practices/

**Comment by piepmatz** [comment]
Minimal besser gefällt mir, wenn die production-settings nicht die develop-settings importieren, sondern beide von den default-settings, so wie auch im zweiten Ansatz deines Links.
Womöglich passiert in den dev-settings etwas, was in den production-settings nicht passiert. Das müsste dann nicht eben nur überschrieben werden, sondern explizit rückgängig gemacht werden. Mit default-settings kommt mir das sauberer vor.
