### ISSUE TITLE
Kontakt für non-profit Optionen bei Google ermitteln

### ISSUE THREAD

**Issue by Bensk1** [Strassengezwitscher/Strassengezwitscher#8]
[Siehe](https://www.google.de/nonprofits/join/)

**Comment by ChristopherSchmidt89** [comment]
Ist denn das ganze schon als gemeinnütziger Verein eingetragen und gibt es einen Standardtext was Strassengezwitscher genau macht?

**Comment by Bensk1** [comment]
Ich habe Alexej schon davon erzählt. Das ist meiner Meinung nach auch eine Aufgabe, die die beiden Chefs am besten erledigen können. Diesen Standardtext sollten auch die beiden haben. Sobald sie sich hier angemeldet haben, werde ich die Aufgabe zuweisen.

Die Eintragung wird noch ein wenig Zeit in Anspruch nehmen.

**Comment by tgraupne** [comment]
Brauchen wir denn unbedingt Google Apps? Ich dachte wir haben einen Root-Server, da können wir doch alles selbst hosten...?

**Comment by Bensk1** [comment]
Es ging um die MapsAPI. Da müssten wir ja sonst OpenStreetMap selbst hosten

**Comment by tgraupne** [comment]
Seid ihr euch mit dem alternativlosen selbst-hosten von OSM sicher? Ich habe auf dem Gebiet keine Erfahrungen, aber als ich vor Wochen nach kurzer Recherche z.B. auf http://leafletjs.com gekommen bin, bin ich noch nirgends drüber gestolpert, dass es eine selbst gehostete OSM-Instanz voraussetzt. Bin ich da komplett falsch gewickelt?

**Comment by ChristopherSchmidt89** [comment]
Die Kartendaten müssen meines Verständnisses nach irgendwoher kommen, leaflet.js nutzt in ihren Beispielen auch nur andere Anbieter e.g. Mapbox, ...
Eine kleine Übersicht habe ich im [Google Drive](https://docs.google.com/document/d/1EVfEYE4aMWgXSMYUsfxsIZyCayBuqA4i2BUJxev8Q9k/edit?usp=sharing) erstellt, meines Erachtens hat man mit Google Maps die meisten gratis Zugriffe auf deren API und auch danach wären sie preislich gesehen ganz gut.
Falls du andere gute Sachen findest, kannst du die gerne ergänzen, bzw. können wir auch andere Anbieter nutzen :-)

**Comment by Bensk1** [comment]
Tom, welchen Account soll ich zum GDrive hinzufügen 

Von meinem iPhone gesendet

**Comment by tgraupne** [comment]
Bitte tgraupne@gmail.com

**Comment by humuzz** [comment]
Also derzeit ist es so, dass wir einen Punkt der ersten Fassung unserer Satzung ändern lassen mussten. Dafür haben wir eine neue Mitgliederversammlung einberufen müssen. Wir haben die Satzungsänderung eingereicht, aber laut Rechtspflegerin haben wir da einen Fehler gemacht. Den müssen wir jetzt (wohl ohne neue MV) beheben, dann ist der Verein registriert. Die Satzung wurde in Absprache mit dem Finanzamt verfasst, sodass hier keine Probleme sein müssten. Dauert halt nur. Selbst wenn wir die Gemeinnützigkeit übernächste Woche beantragen können, dauert ja auch die Bearbeitung des Antrags. So aktuell der Stand.

**Comment by Bensk1** [comment]
Gut. Das hat ja auch ein bisschen Zeit.

**Comment by humuzz** [comment]
Update: Der Verein ist unter VR 9118 am Amtsgericht Dresden registriert. Nun wird die Gemeinnützigkeit beantragt.

**Comment by humuzz** [comment]
Wir haben die Gemeinnützigkeit. Ich beantrage das jetzt.

**Comment by humuzz** [comment]
Google for non profits ist akzeptiert. Brauchen wir das noch für irgendwas?

**Comment by Bensk1** [comment]
ReCaptcha @ChristopherSchmidt89 ?
MapsKey @mathebox ?

Weißt du für welche Produkte von Google das gilt? Dann könnte man eventuell sogar das Hosting dort abwickeln.

**Comment by humuzz** [comment]
- Google Apps für Non-Profits
- Google Ad Grants
- YouTube für Non-Profits 

Das erste ist für euch ja interessant. Ich melde mich dort mal an und schaue, was man da alles machen kann.

**Comment by Bensk1** [comment]
Ja, dann könnte man eventuell den Mailserver, den wir bei einem Provider haben abmelden und das komplett über Google laufen lassen, das würde dauerhafte Kosten sparen. Für Euch bedeutet es ne ganze Menge Cloud-Storage für Dokumente.

**Comment by mathebox** [comment]
closed?
