### ISSUE TITLE
Settings und WSGI aus Code-Abdeckungsreport entfernen

### ISSUE THREAD

**Issue by mathebox** [Strassengezwitscher/Strassengezwitscher#80]
Macht wenig Sinn dafür eine Code-Abdeckung zu machen...

**Comment by mathebox** [comment]
Die migrations brauchen auch keine coverage.

**Comment by mathebox** [comment]
Eine `.coveragerc`-Datei wäre auch schön :) [Link](https://github.com/coagulant/coveralls-python#tips-for-coveragerc-config)

Könntest du es auch gleich so konfigurieren, dass der Code-Abdeckungsreport von `/` startet und nicht erst von `/strassengezwitscher/`? Das wäre gut, wenn die Tests für Angular einabuen.

**Comment by piepmatz** [comment]
`.coveragerc` klingt gut.

Afaik misst coverage.py aber nur Python Code, für Angular brauchen wir also ein anderes Tool. Von daher können wir schon weiterhin von `/strassengezwitscher/` aus starten.

**Comment by mathebox** [comment]
Guck mal auf die gleiche Readme-Seite, der Abschnitt dadrüber ;) [Link](https://github.com/coagulant/coveralls-python#multiple-languages-experimental)
Da wird erklärt wie man mehrere Sprachen mit coveralls unterstützen kann. Der Angular-Report würde sich dann auf `/frontend/` beziehen und django auf `/strassengezwtischer/`.
In der `.coveragerc` müsste dann erstmal nur sowas stehen:
```
[paths]
source = strassengezwitscher/
```

**Comment by piepmatz** [comment]
Oh, das wäre natürlich in der Tat sehr cool, wenn die Coverage-Tools ein einheitliches Format haben.
